# Generated by Django 4.1 on 2022-11-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productcatalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture2',
        ),
    ]
