# Generated by Django 4.1 on 2022-11-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productcatalog', '0002_remove_product_picture2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture1',
            new_name='picture',
        ),
    ]
