# Generated by Django 4.1 on 2022-11-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcatalog', '0003_rename_picture1_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
